kassikos/NewDiplwm

app/src/main/java/com/example/newdiplwm/ObjectSelector.java, app/src/main/java/com/example/newdiplwm/ShadowGame.java, app/src/main/res/layout-land/activity_shadow_game.xml, app/src/main/res/layout/activity_shadow_game.xml, app/src/main/res/values/strings.xml
=> shadowGame beta - 03 game completed rotation completed

app/src/main/java/com/example/newdiplwm/ScalingGame.java, app/src/main/res/values/strings.xml
=> Calcution - REPUSH to textQuestion giati ta eixa valei anapoda

app/src/main/AndroidManifest.xml, app/src/main/java/com/example/newdiplwm/ScalingGame.java, app/src/main/java/com/example/newdiplwm/ShadowGame.java, app/src/main/java/com/example/newdiplwm/UserViewModel.java
Ο timer δεν γινοταν να γινει parce gt einai abstract class αρα αυτο που εκανα ειναι να κραταω το instannce του μεσα στο viewmodel οταν το φτιαχνω και να το κανω retrieve οταν αλλαζει το configuration
=> shadowGame completed

app/src/main/java/com/example/newdiplwm/OrderGame.java, app/src/main/res/values/strings.xml
=> Vasilis branch

app/src/main/java/com/example/newdiplwm/Suitcase.java, app/src/main/java/com/example/newdiplwm/SuitcaseAdv.java, app/src/main/java/com/example/newdiplwm/SuitcaseEz.java, app/src/main/res/layout/suitcase_ez_layout.xml
paikse k pes gnwmh
ekremmei an valoume kapoio plegma gia na fainontai kalutera oi theseis pou mporei na valei
kai an den saresei kati sto kleisimo ths valitsas kai sthn emfanish tou PopUp
=> PR me sxedon teleiwmenh valitsa

app/src/main/res/layout/suitcase_adv_layout.xml
xwris na mikrainoun ta antikeimena
=> megaluterh valitsa sto med kai sto adv

app/src/main/java/com/example/newdiplwm/GameList.java, app/src/main/java/com/example/newdiplwm/MemoryMatrix.java, app/src/main/java/com/example/newdiplwm/SoundWord.java, app/src/main/res/layout-land/activity_scaling_game.xml
Issues pending:
να εξαφανιζεται το κουμπι επομενος γυρος στο τελος των παιχνιδιων
στη game list το OnBack κουμπι να βγαζει μηνυμα εξοδου
=> Some Issues completed

app/src/main/java/com/example/newdiplwm/SuitcaseAdv.java, app/src/main/java/com/example/newdiplwm/SuitcaseEz.java, app/src/main/res/layout/activity_suitcase.xml, app/src/main/res/layout/suitcase_adv_layout.xml, app/src/main/res/layout/suitcase_ez_layout.xml
=> text kai imageview sthn valitsa DONE

app/src/main/AndroidManifest.xml, app/src/main/java/com/example/newdiplwm/AudioPersonPick.java, app/src/main/java/com/example/newdiplwm/Charts.java, app/src/main/java/com/example/newdiplwm/GameAdapter.java, app/src/main/java/com/example/newdiplwm/GameHelper.java, app/src/main/java/com/example/newdiplwm/GameList.java, app/src/main/java/com/example/newdiplwm/Login.java, app/src/main/java/com/example/newdiplwm/MemoryMatrix.java, app/src/main/java/com/example/newdiplwm/ObjectSelector.java, app/src/main/java/com/example/newdiplwm/OrderGame.java, app/src/main/java/com/example/newdiplwm/RockPaperScissors.java, app/src/main/java/com/example/newdiplwm/ScalingGame.java, app/src/main/java/com/example/newdiplwm/Session.java, app/src/main/java/com/example/newdiplwm/Settings.java, app/src/main/java/com/example/newdiplwm/ShadowGame.java, app/src/main/java/com/example/newdiplwm/SoundImage.java, app/src/main/java/com/example/newdiplwm/SoundWord.java, app/src/main/java/com/example/newdiplwm/StatisticAdapter.java, app/src/main/java/com/example/newdiplwm/StatisticsTable.java, app/src/main/java/com/example/newdiplwm/Suitcase.java, app/src/main/java/com/example/newdiplwm/UserGameStatsDao.java, app/src/main/java/com/example/newdiplwm/UserRepository.java, app/src/main/java/com/example/newdiplwm/UserViewModel.java, app/src/main/res/layout-land/activity_sound_image.xml, app/src/main/res/layout/activity_charts.xml, app/src/main/res/values/strings.xml
=> res added , game 10 completed

app/src/main/java/com/example/newdiplwm/GameList.java, app/src/main/java/com/example/newdiplwm/ScalingGame.java, app/src/main/java/com/example/newdiplwm/StatisticsTable.java, app/src/main/res/values/strings.xml
diorthosi tou titlou "Στατιστικά"
h eksodos apo thn efarmogh ginetai me thn FinishAffinity()
tsekare thn, einai gia na kleinei teleiws kai oxi na se petaei sthn login
sto parathiraki eksodou ta allaksa sta ellhnika ta mhnymata kai to koumpi NAI
ena pio wraio prasino sto ScalingGame
dld paikse to paixnidi arithmwn kane swsto k pes mou gia to xrwma
=> 3 Issues solved, check and merge

app/src/main/java/com/example/newdiplwm/GameList.java, app/src/main/java/com/example/newdiplwm/Session.java, app/src/main/res/xml/settings_prefs.xml
=> session bug fixed

app/src/main/AndroidManifest.xml, app/src/main/java/com/example/newdiplwm/Question10.java, app/src/main/res/layout/question_eight.xml, app/src/main/res/layout/question_five.xml, app/src/main/res/layout/question_four.xml, app/src/main/res/layout/question_nine.xml, app/src/main/res/layout/question_one.xml, app/src/main/res/layout/question_seven.xml, app/src/main/res/layout/question_six.xml, app/src/main/res/layout/question_ten.xml, app/src/main/res/layout/question_three.xml, app/src/main/res/layout/question_two.xml, app/src/main/res/values/strings.xml
bug in rate fixed, xml updated
=> bug in rate fixed, xml updated

.idea/codeStyles/Project.xml, app/src/main/java/com/example/newdiplwm/GameList.java, app/src/main/java/com/example/newdiplwm/OrderGame.java, app/src/main/java/com/example/newdiplwm/Question10.java, app/src/main/java/com/example/newdiplwm/RockPaperScissors.java, app/src/main/java/com/example/newdiplwm/ScalingGame.java, app/src/main/java/com/example/newdiplwm/Session.java, app/src/main/java/com/example/newdiplwm/ShadowGame.java, app/src/main/java/com/example/newdiplwm/Tutorial.java, app/src/main/res/layout-land/activity_scaling_game.xml, app/src/main/res/layout-land/custom_tutorial_popup.xml, app/src/main/res/layout/custom_popup.xml, app/src/main/res/layout/custom_tutorial_popup.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/settings_prefs.xml, build.gradle, gradle/wrapper/gradle-wrapper.properties
english words fixed in games , bug in videoView fixed , session updated , menu updated
=> english words fixed in games , bug in videoView fixed , session updated , menu updated

app/src/main/java/com/example/newdiplwm/AudioPersonPick.java, app/src/main/java/com/example/newdiplwm/GameList.java, app/src/main/java/com/example/newdiplwm/MenuChart.java, app/src/main/java/com/example/newdiplwm/ObjectSelector.java, app/src/main/java/com/example/newdiplwm/OrderGame.java, app/src/main/java/com/example/newdiplwm/RockPaperScissors.java, app/src/main/java/com/example/newdiplwm/ScalingGame.java, app/src/main/java/com/example/newdiplwm/ShadowGame.java, app/src/main/java/com/example/newdiplwm/SoundImage.java, app/src/main/java/com/example/newdiplwm/Suitcase.java
bugs in games and tutorial fixed ,minor changes in GameList and barcart name changed
=> bugs in games and tutorial fixed ,minor changes in GameList and barcart name changed

app/src/main/java/com/example/newdiplwm/BucketGame.java, app/src/main/java/com/example/newdiplwm/Register.java, app/src/main/java/com/example/newdiplwm/RockPaperScissors.java
-Medium diff added in BoXGame
-Register bug fixed (if birthdate is null beacuse user dont pick one or education is null for the same reason ) both of them are initialised in default values
=> Medium diff added in BoXGame, minor bugs fixed

app/src/main/AndroidManifest.xml, app/src/main/java/com/example/newdiplwm/AboutActivity.java, app/src/main/java/com/example/newdiplwm/GameAdapter.java, app/src/main/java/com/example/newdiplwm/GameList.java, app/src/main/res/layout-land/activity_about.xml, app/src/main/res/layout-large-land/activity_about.xml, app/src/main/res/layout-large/activity_about.xml, app/src/main/res/layout-xlarge-land/activity_about.xml, app/src/main/res/layout-xlarge/activity_about.xml, app/src/main/res/layout/activity_about.xml
aboutPage added both land and port mode, clean code ,  monor bugs fixed
=> aboutPage added both land and port mode, clean code ,  monor bugs fixed

app/src/main/java/com/example/newdiplwm/Register.java
=> bug fixed in register

app/src/main/java/com/example/newdiplwm/RotationGame.java, app/src/main/res/layout-large/activity_rotation_game.xml, app/src/main/res/layout-xlarge/activity_rotation_game.xml, app/src/main/res/layout/activity_rotation_game.xml
=> RotationGame shapes in all three levels added

app/src/main/java/com/example/newdiplwm/RockPaperScissors.java, app/src/main/java/com/example/newdiplwm/ScalingGame.java, app/src/main/res/layout-land/activity_scaling_game.xml, app/src/main/res/layout-large-land/activity_scaling_game.xml, app/src/main/res/layout-xlarge-land/activity_scaling_game.xml, app/src/main/res/values/strings.xml
RPS game more time per round
ScallingGame feat added
=> RPS game more time per round

app/src/main/java/com/example/newdiplwm/MemoryMatrix.java, app/src/main/res/layout-large/activity_memory_matrix.xml, app/src/main/res/layout-xlarge/activity_memory_matrix.xml, app/src/main/res/layout/activity_memory_matrix.xml
=> MemoryMatrixGame feat added

app/src/main/java/com/example/newdiplwm/OrderGame.java, app/src/main/java/com/example/newdiplwm/RockPaperScissors.java, app/src/main/res/layout-large/activity_order_game.xml, app/src/main/res/layout-xlarge/activity_order_game.xml, app/src/main/res/layout/activity_order_game.xml
=> OG game feat added

app/src/main/java/com/example/newdiplwm/ObjectSelector.java, app/src/main/res/layout-land/activity_object_selector.xml, app/src/main/res/layout-large-land/activity_object_selector.xml, app/src/main/res/layout-large/activity_object_selector.xml, app/src/main/res/layout-xlarge-land/activity_object_selector.xml, app/src/main/res/layout-xlarge/activity_object_selector.xml, app/src/main/res/layout/activity_object_selector.xml
=> OS game feat added

app/src/main/java/com/example/newdiplwm/Suitcase.java, app/src/main/java/com/example/newdiplwm/SuitcaseAdv.java, app/src/main/java/com/example/newdiplwm/SuitcaseEz.java, app/src/main/res/layout-large/activity_suitcase.xml, app/src/main/res/layout-xlarge/activity_suitcase.xml, app/src/main/res/layout/activity_suitcase.xml
=> Suitcase game feat added

app/src/main/java/com/example/newdiplwm/RotationGame.java, app/src/main/java/com/example/newdiplwm/SuitcaseAdv.java, app/src/main/java/com/example/newdiplwm/SuitcaseEz.java
User always has to rotate inorder to answer correctly
=> RotationGame bug fixed

app/src/main/java/com/example/newdiplwm/AudioPersonPick.java, app/src/main/java/com/example/newdiplwm/BucketGame.java, app/src/main/java/com/example/newdiplwm/MemoryMatrix.java, app/src/main/java/com/example/newdiplwm/ObjectSelector.java, app/src/main/java/com/example/newdiplwm/OrderGame.java, app/src/main/java/com/example/newdiplwm/RockPaperScissors.java, app/src/main/java/com/example/newdiplwm/ScalingGame.java, app/src/main/java/com/example/newdiplwm/ShadowGame.java, app/src/main/java/com/example/newdiplwm/SoundImage.java, app/src/main/java/com/example/newdiplwm/SoundWord.java, app/src/main/java/com/example/newdiplwm/Suitcase.java, app/src/main/java/com/example/newdiplwm/Tutorial.java, app/src/main/res/layout-large/activity_bucket_game.xml, app/src/main/res/layout-xlarge/activity_bucket_game.xml, app/src/main/res/layout/activity_bucket_game.xml
bucketGame Feat added
on lock tutorial not display while playing
=> bucketGame Feat added

app/src/main/java/com/example/newdiplwm/AudioPersonPick.java, app/src/main/java/com/example/newdiplwm/BucketGame.java, app/src/main/java/com/example/newdiplwm/MemoryMatrix.java, app/src/main/java/com/example/newdiplwm/ObjectSelector.java, app/src/main/java/com/example/newdiplwm/OrderGame.java, app/src/main/java/com/example/newdiplwm/RockPaperScissors.java, app/src/main/java/com/example/newdiplwm/ScalingGame.java, app/src/main/java/com/example/newdiplwm/ShadowGame.java, app/src/main/java/com/example/newdiplwm/SoundImage.java, app/src/main/java/com/example/newdiplwm/SoundWord.java, app/src/main/java/com/example/newdiplwm/Suitcase.java
scalling game fixed
rps game feat enable/disable tutorials added
rps game bug fixed on advanced mode when expire timer and rotate the same time
=> scalling game fixed

app/src/main/java/com/example/newdiplwm/AudioPersonPick.java, app/src/main/java/com/example/newdiplwm/SoundImage.java, app/src/main/java/com/example/newdiplwm/SoundWord.java
on screen lock game freeze fixed (all audio games)
=> on screen lock game freeze fixed (all audio games)

app/src/main/java/com/example/newdiplwm/AudioPersonPick.java, app/src/main/java/com/example/newdiplwm/BucketGame.java, app/src/main/java/com/example/newdiplwm/MemoryMatrix.java, app/src/main/java/com/example/newdiplwm/ObjectSelector.java, app/src/main/java/com/example/newdiplwm/OrderGame.java, app/src/main/java/com/example/newdiplwm/RockPaperScissors.java, app/src/main/java/com/example/newdiplwm/ScalingGame.java, app/src/main/java/com/example/newdiplwm/ShadowGame.java, app/src/main/java/com/example/newdiplwm/SoundImage.java, app/src/main/java/com/example/newdiplwm/SoundWord.java, app/src/main/java/com/example/newdiplwm/Suitcase.java, app/src/main/res/values/strings.xml
=> punctuation in next round msg

app/src/main/java/com/example/newdiplwm/AudioPersonPick.java, app/src/main/java/com/example/newdiplwm/BucketGame.java, app/src/main/java/com/example/newdiplwm/MemoryMatrix.java, app/src/main/java/com/example/newdiplwm/MenuChart.java, app/src/main/java/com/example/newdiplwm/ObjectSelector.java, app/src/main/java/com/example/newdiplwm/OrderGame.java, app/src/main/java/com/example/newdiplwm/RockPaperScissors.java, app/src/main/java/com/example/newdiplwm/RotationGame.java, app/src/main/java/com/example/newdiplwm/ScalingGame.java, app/src/main/java/com/example/newdiplwm/ShadowGame.java, app/src/main/java/com/example/newdiplwm/SoundImage.java, app/src/main/java/com/example/newdiplwm/SoundWord.java, app/src/main/java/com/example/newdiplwm/StatisticAdapter.java, app/src/main/java/com/example/newdiplwm/Suitcase.java, app/src/main/java/com/example/newdiplwm/SuitcaseAdv.java, app/src/main/java/com/example/newdiplwm/SuitcaseEz.java, app/src/main/res/values/myColors.xml
texts changed , mins/secs changed
rps feat added on rotate display dif tutorial
=> texts changed , mins/secs changed

app/src/main/res/layout-land/activity_rotation_game.xml, app/src/main/res/layout-large-land/activity_rotation_game.xml
=> rotation game: layouts fixed

app/src/main/java/com/example/newdiplwm/ShadowGame.java
=> shadowGame tut added

app/src/main/java/com/example/newdiplwm/RotationGame.java
rotation game bug fixed on screen configuration
=> rotation game bug fixed on screen configuration

app/src/main/java/com/example/newdiplwm/GameHelper.java, app/src/main/java/com/example/newdiplwm/GameList.java, app/src/main/java/com/example/newdiplwm/Tutorial.java, app/src/main/res/layout-land/activity_rotation_game.xml, app/src/main/res/layout-large-land/activity_rotation_game.xml, app/src/main/res/layout-large/activity_rotation_game.xml, app/src/main/res/layout-xlarge-land/activity_rotation_game.xml, app/src/main/res/layout-xlarge/activity_rotation_game.xml, app/src/main/res/layout/activity_rotation_game.xml
export db feat fixed
rotation game borded gone
=> export db feat fixed

app/src/main/res/layout-land/activity_scaling_game.xml, app/src/main/res/layout-large-land/activity_scaling_game.xml, app/src/main/res/layout-large/activity_memory_matrix.xml, app/src/main/res/layout-xlarge-land/activity_scaling_game.xml, app/src/main/res/layout-xlarge/activity_memory_matrix.xml, app/src/main/res/layout/activity_memory_matrix.xml
MMG , RPS , SCG texts land and portrait
=> MMG , RPS , SCG texts land and portrait

app/src/main/res/layout-land/activity_object_selector.xml, app/src/main/res/layout-land/activity_rotation_game.xml, app/src/main/res/layout-land/activity_shadow_game.xml, app/src/main/res/layout-land/activity_sound_word.xml, app/src/main/res/layout-large-land/activity_object_selector.xml, app/src/main/res/layout-large-land/activity_rotation_game.xml, app/src/main/res/layout-large-land/activity_shadow_game.xml, app/src/main/res/layout-large-land/activity_sound_word.xml, app/src/main/res/layout-large/activity_memory_matrix.xml, app/src/main/res/layout-xlarge-land/activity_object_selector.xml, app/src/main/res/layout-xlarge-land/activity_rotation_game.xml, app/src/main/res/layout-xlarge-land/activity_shadow_game.xml, app/src/main/res/layout-xlarge-land/activity_sound_word.xml, app/src/main/res/layout-xlarge/activity_memory_matrix.xml, app/src/main/res/layout/activity_memory_matrix.xml
congrats text in land mode is larger
=> congrats text in land mode is larger
